apiVersion: v1
kind: Service
metadata:
  name: http-echo-demo
spec:
  selector:
    app: http-echo-demo
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 5678
  type: ClusterIP
