apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-demo
  labels:
    servicename: backend
    commit: "69ecc01d96ac3c7e141d3e8256ce0b360af16609"
    message: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-demo
  template:
    metadata:
      labels:
        app: httpd-demo
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.51   # Change version tag to trigger Argo
        ports:
          - containerPort: 80
